/* host build stand-in for the generated sdkconfig.h (defaults of main/Kconfig.projbuild) */
#ifndef CONFIG_GYROLOG_MOUNT_UP_USB_RIGHT
#define CONFIG_GYROLOG_MOUNT_UP_USB_RIGHT 1
#endif
#define CONFIG_GYROLOG_ODR_HZ 200
#define CONFIG_GYROLOG_GYRO_DPS 1000
#define CONFIG_GYROLOG_ACC_G 8
#define CONFIG_GYROLOG_LOG_ACCEL 1
#define CONFIG_GYROLOG_MAIN_BUTTON_GPIO 11
#define CONFIG_GYROLOG_AUX_BUTTON_GPIO 12
#define CONFIG_GYROLOG_LONG_PRESS_MS 1200
#define CONFIG_GYROLOG_IDLE_SLEEP_S 60
#define CONFIG_GYROLOG_REC_SCREEN_S 3
#define CONFIG_GYROLOG_LCD_BRIGHTNESS 40
#define CONFIG_GYROLOG_FIFO_POLL_MS 160
#define CONFIG_GYROLOG_LOW_BATT_MV 3350
#define CONFIG_GYROLOG_LIGHT_SLEEP_REC 1
